---
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/tetsu/smokepingdata/config:/config
      - /home/tetsu/smokepingdata/data:/data
    ports:
      - 8081:80
    restart: unless-stopped
